// src/app/features/reimbursements/reimbursement-detail/reimbursement-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { ReimbursementService } from '../../../core/services/reimbursement.service';
import { ReimbursementDetail, ReimbursementStatus } from '../../../core/models/reimbursement.model';

@Component({
  selector: 'app-reimbursement-detail',
  standalone: true,
  imports: [CommonModule, RouterLink],
  templateUrl: './reimbursement-detail.component.html',
  styleUrl: './reimbursement-detail.component.scss'
})
export class ReimbursementDetailComponent implements OnInit {
  detalle: ReimbursementDetail | undefined;
  estadoActual: ReimbursementStatus = 'Pendiente';
  estadoOriginal: ReimbursementStatus = 'Pendiente';
  isLoading = true;
  notFound = false;

  constructor(
    private route: ActivatedRoute,
    private reimbursementService: ReimbursementService
  ) {}

  ngOnInit(): void {
    const id = this.route.snapshot.paramMap.get('id');
    if (id) {
      this.loadReimbursement(id);
    } else {
      this.notFound = true;
      this.isLoading = false;
    }
  }

  private loadReimbursement(id: string): void {
    this.reimbursementService.getReimbursementById(id).subscribe(data => {
      if (data) {
        this.detalle = data;
        this.estadoActual = data.estado;
        this.estadoOriginal = data.estado;
      } else {
        this.notFound = true;
      }
      this.isLoading = false;
    });
  }

  cambiarEstado(nuevoEstado: ReimbursementStatus): void {
    if (this.detalle && this.estadoActual !== nuevoEstado) {
      this.reimbursementService.updateReimbursementStatus(this.detalle.id, nuevoEstado)
        .subscribe(success => {
          if (success) {
            this.estadoActual = nuevoEstado;
            console.log(`Estado cambiado de "${this.estadoOriginal}" a "${nuevoEstado}"`);
          }
        });
    }
  }

  getEstadoClass(estado: string): string {
    switch (estado) {
      case 'Aprobado':
        return 'estado-aprobado';
      case 'Pendiente':
        return 'estado-pendiente';
      case 'En revisión':
        return 'estado-revision';
      case 'Rechazado':
        return 'estado-rechazado';
      default:
        return 'estado-default';
    }
  }

  formatCurrency(value: number): string {
    return value.toLocaleString('es-MX', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  }

  formatDate(dateString: string): string {
    return new Date(dateString).toLocaleDateString('es-MX', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });
  }

  formatDateTime(dateString: string): string {
    return new Date(dateString).toLocaleString('es-MX', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  }

  calcularImporte(cantidad: number, precioUnitario: number): number {
    return cantidad * precioUnitario;
  }

  descargarXML(): void {
    console.log('Descargando XML...');
  }

  descargarPDF(numero: number): void {
    console.log(`Descargando PDF ${numero}...`);
  }
}

@if (isLoading) {
  <div class="loading-container">
    <p>Cargando...</p>
  </div>
} @else if (notFound) {
  <div class="not-found-container">
    <p class="not-found-text">Reembolso no encontrado</p>
    <a routerLink="/" class="back-link">Volver al dashboard</a>
  </div>
} @else if (detalle) {
  <div class="detail-container">
    <!-- Header -->
    <div class="detail-header">
      <a routerLink="/" class="back-link">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <line x1="19" y1="12" x2="5" y2="12"/>
          <polyline points="12 19 5 12 12 5"/>
        </svg>
        Volver al dashboard
      </a>
      <div class="header-content">
        <div class="header-text">
          <h1>{{ detalle.asunto }}</h1>
          <p class="subtitle">Detalle de la solicitud de reembolso</p>
        </div>
        <span class="estado-badge" [ngClass]="getEstadoClass(estadoActual)">
          {{ estadoActual }}
        </span>
      </div>
    </div>

    <div class="detail-grid">
      <!-- Columna principal -->
      <div class="main-column">
        <!-- Información general -->
        <div class="card">
          <h2 class="card-title">Información General</h2>
          <div class="info-grid">
            <div class="info-item">
              <div class="info-icon blue">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                  <rect x="3" y="4" width="18" height="18" rx="2" ry="2"/>
                  <line x1="16" y1="2" x2="16" y2="6"/>
                  <line x1="8" y1="2" x2="8" y2="6"/>
                  <line x1="3" y1="10" x2="21" y2="10"/>
                </svg>
              </div>
              <div class="info-content">
                <p class="info-label">Fecha de solicitud</p>
                <p class="info-value">{{ formatDate(detalle.fecha) }}</p>
              </div>
            </div>

            <div class="info-item">
              <div class="info-icon purple">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                  <path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z"/>
                  <polyline points="14,2 14,8 20,8"/>
                </svg>
              </div>
              <div class="info-content">
                <p class="info-label">Solicitante</p>
                <p class="info-value">{{ detalle.remitente }}</p>
              </div>
            </div>

            <div class="info-item">
              <div class="info-icon green">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                  <line x1="4" y1="9" x2="20" y2="9"/>
                  <line x1="4" y1="15" x2="20" y2="15"/>
                  <line x1="10" y1="3" x2="8" y2="21"/>
                  <line x1="16" y1="3" x2="14" y2="21"/>
                </svg>
              </div>
              <div class="info-content">
                <p class="info-label">UUID</p>
                <p class="info-value uuid">{{ detalle.uuid }}</p>
              </div>
            </div>

            <div class="info-item">
              <div class="info-icon orange">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                  <line x1="12" y1="1" x2="12" y2="23"/>
                  <path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"/>
                </svg>
              </div>
              <div class="info-content">
                <p class="info-label">Monto total</p>
                <p class="info-value total">${{ formatCurrency(detalle.total) }}</p>
              </div>
            </div>
          </div>

          <div class="description-section">
            <p class="info-label">Descripción</p>
            <p class="description-text">{{ detalle.descripcion }}</p>
          </div>
        </div>

        <!-- Conceptos -->
        <div class="card">
          <h2 class="card-title">Conceptos</h2>
          <div class="table-wrapper">
            <table>
              <thead>
                <tr>
                  <th class="text-left">Descripción</th>
                  <th class="text-center">Cantidad</th>
                  <th class="text-right">Precio Unitario</th>
                  <th class="text-right">Importe</th>
                </tr>
              </thead>
              <tbody>
                @for (concepto of detalle.conceptos; track $index) {
                  <tr>
                    <td>{{ concepto.descripcion }}</td>
                    <td class="text-center">{{ concepto.cantidad }}</td>
                    <td class="text-right">${{ formatCurrency(concepto.precioUnitario) }}</td>
                    <td class="text-right font-medium">${{ formatCurrency(calcularImporte(concepto.cantidad, concepto.precioUnitario)) }}</td>
                  </tr>
                }
              </tbody>
              <tfoot>
                <tr>
                  <td colspan="3" class="text-right font-semibold">Total:</td>
                  <td class="text-right total-value">${{ formatCurrency(detalle.total) }}</td>
                </tr>
              </tfoot>
            </table>
          </div>
        </div>
      </div>

      <!-- Sidebar derecha -->
      <div class="sidebar-column">
        <!-- Documentos -->
        <div class="card">
          <h2 class="card-title">Documentos</h2>
          <div class="documents-list">
            <button class="document-btn" (click)="descargarXML()">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
                <polyline points="7,10 12,15 17,10"/>
                <line x1="12" y1="15" x2="12" y2="3"/>
              </svg>
              <div class="document-info">
                <p class="document-title">Descargar XML</p>
                <p class="document-subtitle">Factura electrónica</p>
              </div>
            </button>

            <button class="document-btn" (click)="descargarPDF(1)">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
                <polyline points="7,10 12,15 17,10"/>
                <line x1="12" y1="15" x2="12" y2="3"/>
              </svg>
              <div class="document-info">
                <p class="document-title">Descargar PDF 1</p>
                <p class="document-subtitle">Representación impresa</p>
              </div>
            </button>

            <button class="document-btn" (click)="descargarPDF(2)">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
                <polyline points="7,10 12,15 17,10"/>
                <line x1="12" y1="15" x2="12" y2="3"/>
              </svg>
              <div class="document-info">
                <p class="document-title">Descargar PDF 2</p>
                <p class="document-subtitle">Comprobante adicional</p>
              </div>
            </button>
          </div>
        </div>

        <!-- Información fiscal -->
        <div class="card">
          <h2 class="card-title">Información Fiscal</h2>
          <div class="fiscal-info">
            <div class="fiscal-item">
              <p class="info-label">RFC Emisor</p>
              <p class="info-value mono">{{ detalle.rfcEmisor }}</p>
            </div>

            <div class="fiscal-item">
              <p class="info-label">RFC Receptor</p>
              <p class="info-value mono">{{ detalle.rfcReceptor }}</p>
            </div>

            <div class="fiscal-item">
              <p class="info-label">Fecha de Timbrado</p>
              <p class="info-value">{{ formatDateTime(detalle.fechaTimbrado) }}</p>
            </div>

            <div class="fiscal-item">
              <p class="info-label">Monto Total</p>
              <p class="info-value total">${{ formatCurrency(detalle.total) }}</p>
            </div>
          </div>
        </div>

        <!-- Acciones -->
        <div class="card">
          <h2 class="card-title">Cambiar Estado</h2>
          <div class="action-buttons">
            <button
              class="action-btn aprobar"
              [class.disabled]="estadoActual === 'Aprobado'"
              [disabled]="estadoActual === 'Aprobado'"
              (click)="cambiarEstado('Aprobado')"
            >
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/>
                <polyline points="22,4 12,14.01 9,11.01"/>
              </svg>
              Aprobar
            </button>

            <button
              class="action-btn revision"
              [class.disabled]="estadoActual === 'En revisión'"
              [disabled]="estadoActual === 'En revisión'"
              (click)="cambiarEstado('En revisión')"
            >
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <circle cx="12" cy="12" r="10"/>
                <polyline points="12,6 12,12 16,14"/>
              </svg>
              En revisión
            </button>

            <button
              class="action-btn rechazar"
              [class.disabled]="estadoActual === 'Rechazado'"
              [disabled]="estadoActual === 'Rechazado'"
              (click)="cambiarEstado('Rechazado')"
            >
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <circle cx="12" cy="12" r="10"/>
                <line x1="15" y1="9" x2="9" y2="15"/>
                <line x1="9" y1="9" x2="15" y2="15"/>
              </svg>
              Rechazar
            </button>

            <button
              class="action-btn pendiente"
              [class.disabled]="estadoActual === 'Pendiente'"
              [disabled]="estadoActual === 'Pendiente'"
              (click)="cambiarEstado('Pendiente')"
            >
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/>
                <polyline points="22,4 12,14.01 9,11.01"/>
              </svg>
              Pendiente
            </button>
          </div>

          @if (estadoActual !== estadoOriginal) {
            <div class="status-change-notice">
              <p>
                <strong>Estado actualizado:</strong> El reembolso ahora está marcado como "{{ estadoActual }}"
              </p>
            </div>
          }
        </div>
      </div>
    </div>
  </div>
}

// muestra/ReimbursementDetail.tsx
import { useParams, Link } from "react-router";
import { ArrowLeft, Download, FileText, Calendar, Building2, Hash, DollarSign, CheckCircle2, XCircle, Clock } from "lucide-react";
import { useState } from "react";

// Mock data detallado
const mockReimbursementDetails = {
  "1": {
    id: "1",
    fecha: "2026-03-01",
    remitente: "Juan Pérez García",
    asunto: "Gastos de conferencia académica",
    uuid: "A1B2C3D4-E5F6-7890-ABCD-EF1234567890",
    total: 8500.00,
    estado: "Aprobado",
    rfcEmisor: "ABC123456DEF",
    rfcReceptor: "UNI987654321",
    fechaTimbrado: "2026-03-01T10:30:00",
    descripcion: "Reembolso de gastos por participación en la Conferencia Internacional de Educación Superior celebrada en Guadalajara, incluyendo transporte, hospedaje y registro.",
    conceptos: [
      { descripcion: "Transporte aéreo redondo", cantidad: 1, precioUnitario: 3500.00 },
      { descripcion: "Hospedaje (3 noches)", cantidad: 3, precioUnitario: 1200.00 },
      { descripcion: "Registro conferencia", cantidad: 1, precioUnitario: 2100.00 },
    ],
  },
  "2": {
    id: "2",
    fecha: "2026-03-02",
    remitente: "María López Hernández",
    asunto: "Material didáctico",
    uuid: "B2C3D4E5-F6G7-8901-BCDE-F12345678901",
    total: 3200.50,
    estado: "Pendiente",
    rfcEmisor: "XYZ789012GHI",
    rfcReceptor: "UNI987654321",
    fechaTimbrado: "2026-03-02T14:20:00",
    descripcion: "Compra de material didáctico para el curso de Matemáticas Aplicadas del semestre actual.",
    conceptos: [
      { descripcion: "Libros de texto", cantidad: 15, precioUnitario: 180.00 },
      { descripcion: "Material de papelería", cantidad: 1, precioUnitario: 500.50 },
    ],
  },
};

export function ReimbursementDetail() {
  const { id } = useParams<{ id: string }>();
  const detalle = mockReimbursementDetails[id as keyof typeof mockReimbursementDetails];
  const [estadoActual, setEstadoActual] = useState(detalle?.estado || "");

  if (!detalle) {
    return (
      <div className="p-8">
        <div className="text-center py-12">
          <p className="text-gray-500 text-lg">Reembolso no encontrado</p>
          <Link to="/" className="text-[#1e3a5f] hover:underline mt-4 inline-block">
            Volver al dashboard
          </Link>
        </div>
      </div>
    );
  }

  const handleCambiarEstado = (nuevoEstado: string) => {
    setEstadoActual(nuevoEstado);
    // Aquí se haría la llamada a la API para actualizar el estado en el servidor
    console.log(`Estado cambiado de "${detalle.estado}" a "${nuevoEstado}"`);
  };

  const getEstadoColor = (estado: string) => {
    switch (estado) {
      case "Aprobado":
        return "bg-green-100 text-green-800";
      case "Pendiente":
        return "bg-yellow-100 text-yellow-800";
      case "En revisión":
        return "bg-blue-100 text-blue-800";
      case "Rechazado":
        return "bg-red-100 text-red-800";
      default:
        return "bg-gray-100 text-gray-800";
    }
  };

  return (
    <div className="p-8">
      {/* Header */}
      <div className="mb-6">
        <Link
          to="/"
          className="inline-flex items-center gap-2 text-[#1e3a5f] hover:text-[#152d47] transition-colors mb-4"
        >
          <ArrowLeft className="w-4 h-4" />
          Volver al dashboard
        </Link>
        <div className="flex items-start justify-between">
          <div>
            <h1 className="text-2xl font-semibold text-gray-900 mb-2">{detalle.asunto}</h1>
            <p className="text-gray-600">Detalle de la solicitud de reembolso</p>
          </div>
          <span
            className={`px-4 py-2 inline-flex text-sm font-medium rounded-lg ${getEstadoColor(
              estadoActual
            )}`}
          >
            {estadoActual}
          </span>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Columna principal */}
        <div className="lg:col-span-2 space-y-6">
          {/* Información general */}
          <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
            <h2 className="text-lg font-semibold text-gray-900 mb-4">Información General</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="flex items-start gap-3">
                <div className="w-10 h-10 bg-blue-100 rounded-lg flex items-center justify-center flex-shrink-0">
                  <Calendar className="w-5 h-5 text-[#1e3a5f]" />
                </div>
                <div>
                  <p className="text-sm text-gray-600">Fecha de solicitud</p>
                  <p className="font-medium text-gray-900">
                    {new Date(detalle.fecha).toLocaleDateString("es-MX", {
                      year: "numeric",
                      month: "long",
                      day: "numeric",
                    })}
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-3">
                <div className="w-10 h-10 bg-purple-100 rounded-lg flex items-center justify-center flex-shrink-0">
                  <FileText className="w-5 h-5 text-purple-600" />
                </div>
                <div>
                  <p className="text-sm text-gray-600">Solicitante</p>
                  <p className="font-medium text-gray-900">{detalle.remitente}</p>
                </div>
              </div>

              <div className="flex items-start gap-3">
                <div className="w-10 h-10 bg-green-100 rounded-lg flex items-center justify-center flex-shrink-0">
                  <Hash className="w-5 h-5 text-green-600" />
                </div>
                <div>
                  <p className="text-sm text-gray-600">UUID</p>
                  <p className="font-medium text-gray-900 text-xs font-mono">{detalle.uuid}</p>
                </div>
              </div>

              <div className="flex items-start gap-3">
                <div className="w-10 h-10 bg-orange-100 rounded-lg flex items-center justify-center flex-shrink-0">
                  <DollarSign className="w-5 h-5 text-orange-600" />
                </div>
                <div>
                  <p className="text-sm text-gray-600">Monto total</p>
                  <p className="text-xl font-semibold text-gray-900">
                    ${detalle.total.toLocaleString("es-MX", { minimumFractionDigits: 2 })}
                  </p>
                </div>
              </div>
            </div>

            <div className="mt-6 pt-6 border-t border-gray-200">
              <p className="text-sm text-gray-600 mb-2">Descripción</p>
              <p className="text-gray-900 leading-relaxed">{detalle.descripcion}</p>
            </div>
          </div>

          {/* Conceptos */}
          <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
            <h2 className="text-lg font-semibold text-gray-900 mb-4">Conceptos</h2>
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead>
                  <tr className="border-b border-gray-200">
                    <th className="text-left py-3 text-sm font-medium text-gray-600">Descripción</th>
                    <th className="text-center py-3 text-sm font-medium text-gray-600">Cantidad</th>
                    <th className="text-right py-3 text-sm font-medium text-gray-600">Precio Unitario</th>
                    <th className="text-right py-3 text-sm font-medium text-gray-600">Importe</th>
                  </tr>
                </thead>
                <tbody>
                  {detalle.conceptos.map((concepto, index) => (
                    <tr key={index} className="border-b border-gray-100 last:border-0">
                      <td className="py-3 text-sm text-gray-900">{concepto.descripcion}</td>
                      <td className="py-3 text-sm text-gray-900 text-center">{concepto.cantidad}</td>
                      <td className="py-3 text-sm text-gray-900 text-right">
                        ${concepto.precioUnitario.toLocaleString("es-MX", { minimumFractionDigits: 2 })}
                      </td>
                      <td className="py-3 text-sm font-medium text-gray-900 text-right">
                        ${(concepto.cantidad * concepto.precioUnitario).toLocaleString("es-MX", {
                          minimumFractionDigits: 2,
                        })}
                      </td>
                    </tr>
                  ))}
                </tbody>
                <tfoot>
                  <tr className="border-t-2 border-gray-200">
                    <td colSpan={3} className="py-3 text-sm font-semibold text-gray-900 text-right">
                      Total:
                    </td>
                    <td className="py-3 text-lg font-semibold text-gray-900 text-right">
                      ${detalle.total.toLocaleString("es-MX", { minimumFractionDigits: 2 })}
                    </td>
                  </tr>
                </tfoot>
              </table>
            </div>
          </div>
        </div>

        {/* Sidebar derecha */}
        <div className="space-y-6">
          {/* Documentos */}
          <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
            <h2 className="text-lg font-semibold text-gray-900 mb-4">Documentos</h2>
            <div className="space-y-3">
              <button className="w-full flex items-center gap-3 px-4 py-3 border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors">
                <Download className="w-5 h-5 text-[#1e3a5f]" />
                <div className="text-left flex-1">
                  <p className="font-medium text-gray-900 text-sm">Descargar XML</p>
                  <p className="text-xs text-gray-500">Factura electrónica</p>
                </div>
              </button>

              <button className="w-full flex items-center gap-3 px-4 py-3 border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors">
                <Download className="w-5 h-5 text-[#1e3a5f]" />
                <div className="text-left flex-1">
                  <p className="font-medium text-gray-900 text-sm">Descargar PDF 1</p>
                  <p className="text-xs text-gray-500">Representación impresa</p>
                </div>
              </button>

              <button className="w-full flex items-center gap-3 px-4 py-3 border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors">
                <Download className="w-5 h-5 text-[#1e3a5f]" />
                <div className="text-left flex-1">
                  <p className="font-medium text-gray-900 text-sm">Descargar PDF 2</p>
                  <p className="text-xs text-gray-500">Comprobante adicional</p>
                </div>
              </button>
            </div>
          </div>

          {/* Información fiscal */}
          <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
            <h2 className="text-lg font-semibold text-gray-900 mb-4">Información Fiscal</h2>
            <div className="space-y-4">
              <div>
                <p className="text-sm text-gray-600 mb-1">RFC Emisor</p>
                <p className="font-medium text-gray-900 font-mono text-sm">{detalle.rfcEmisor}</p>
              </div>

              <div>
                <p className="text-sm text-gray-600 mb-1">RFC Receptor</p>
                <p className="font-medium text-gray-900 font-mono text-sm">{detalle.rfcReceptor}</p>
              </div>

              <div>
                <p className="text-sm text-gray-600 mb-1">Fecha de Timbrado</p>
                <p className="font-medium text-gray-900">
                  {new Date(detalle.fechaTimbrado).toLocaleString("es-MX", {
                    year: "numeric",
                    month: "long",
                    day: "numeric",
                    hour: "2-digit",
                    minute: "2-digit",
                  })}
                </p>
              </div>

              <div>
                <p className="text-sm text-gray-600 mb-1">Monto Total</p>
                <p className="text-xl font-semibold text-gray-900">
                  ${detalle.total.toLocaleString("es-MX", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                </p>
              </div>
            </div>
          </div>

          {/* Acciones */}
          <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
            <h2 className="text-lg font-semibold text-gray-900 mb-4">Cambiar Estado</h2>
            <div className="space-y-3">
              
              <button
                onClick={() => handleCambiarEstado("Aprobado")}
                disabled={estadoActual === "Aprobado"}
                className={`w-full flex items-center justify-center gap-2 px-4 py-3 rounded-lg transition-colors ${
                  estadoActual === "Aprobado"
                    ? "bg-gray-200 text-gray-500 cursor-not-allowed"
                    : "bg-green-600 text-white hover:bg-green-700"
                }`}
              >
                <CheckCircle2 className="w-5 h-5" />
                Aprobar
              </button>
              
              <button
                onClick={() => handleCambiarEstado("En revisión")}
                disabled={estadoActual === "En revisión"}
                className={`w-full flex items-center justify-center gap-2 px-4 py-3 rounded-lg transition-colors ${
                  estadoActual === "En revisión"
                    ? "bg-gray-200 text-gray-500 cursor-not-allowed"
                    : "bg-blue-600 text-white hover:bg-blue-700"
                }`}
              >
                <Clock className="w-5 h-5" />
                En revisión
              </button>
              
              <button
                onClick={() => handleCambiarEstado("Rechazado")}
                disabled={estadoActual === "Rechazado"}
                className={`w-full flex items-center justify-center gap-2 px-4 py-3 rounded-lg transition-colors ${
                  estadoActual === "Rechazado"
                    ? "bg-gray-200 text-gray-500 cursor-not-allowed"
                    : "bg-red-600 text-white hover:bg-red-700"
                }`}
              >
                <XCircle className="w-5 h-5" />
                Rechazar
              </button>



              <button
                onClick={() => handleCambiarEstado("Pendiente")}
                disabled={estadoActual === "Pendiente"}
                className={`w-full flex items-center justify-center gap-2 px-4 py-3 rounded-lg transition-colors ${
                  estadoActual === "Pendiente"
                    ? "bg-gray-200 text-gray-500 cursor-not-allowed"
                    : "bg-yellow-600 text-white hover:bg-green-700"
                }`}
              >
                <CheckCircle2 className="w-5 h-5" />
                Pendiente
              </button>
              

              
            </div>
            
            {estadoActual !== detalle.estado && (
              <div className="mt-4 p-3 bg-blue-50 border border-blue-200 rounded-lg">
                <p className="text-sm text-blue-800">
                  <strong>Estado actualizado:</strong> El reembolso ahora está marcado como "{estadoActual}"
                </p>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
